spring.application.name=api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.url=${DATABASE-URL}
spring.datasource.username=${DATABASE-USERNAME}
spring.datasource.password=${DATABASE-PASSWORD}
server.port=${PORT}


